-- 0001_init.sql — contacts table, validation constraints, and RLS ownership.
--
-- Applied to the Neon `main` branch of project secure-networking-tracker.
-- This file is the reviewable source of truth for the schema; it is written to
-- be re-runnable against a fresh Neon branch that has Managed Better Auth and
-- the Data API enabled (both provide the `auth` schema).
--
-- Trust model: the browser talks straight to Postgres through the Data API, so
-- there is no application server in the request path to validate on. Every rule
-- below is therefore enforced by Postgres itself and cannot be bypassed by
-- editing client code or calling the REST endpoint directly.

-- 1. Table -------------------------------------------------------------------
-- user_id defaults to auth.user_id(), which returns the `sub` claim of the
-- caller's Better Auth JWT as text. Clients never send it; they cannot forge it.
CREATE TABLE public.contacts (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     text NOT NULL DEFAULT (auth.user_id()),
  name        text NOT NULL,
  company     text,
  role        text,
  met_at      text,
  notes       text,
  priority    text NOT NULL DEFAULT 'medium',
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),

  -- Backend validation. These reject bad data at the database, which is the
  -- only layer a client cannot skip.
  CONSTRAINT contacts_name_not_blank    CHECK (length(trim(name)) > 0),
  CONSTRAINT contacts_name_max_len      CHECK (length(name) <= 200),
  CONSTRAINT contacts_priority_valid    CHECK (priority IN ('high', 'medium', 'low')),
  CONSTRAINT contacts_user_id_not_blank CHECK (length(trim(user_id)) > 0)
);

-- 2. Row Level Security ------------------------------------------------------
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- Separate policy per operation, each restricting access to rows the caller owns.
CREATE POLICY contacts_select_own ON public.contacts
  FOR SELECT TO authenticated
  USING (auth.user_id() = user_id);

CREATE POLICY contacts_insert_own ON public.contacts
  FOR INSERT TO authenticated
  WITH CHECK (auth.user_id() = user_id);

-- USING decides which rows may be updated (you must own the row now).
-- WITH CHECK re-validates the row after the update, which is what stops a user
-- from rewriting user_id to hand their row to someone else.
CREATE POLICY contacts_update_own ON public.contacts
  FOR UPDATE TO authenticated
  USING (auth.user_id() = user_id)
  WITH CHECK (auth.user_id() = user_id);

CREATE POLICY contacts_delete_own ON public.contacts
  FOR DELETE TO authenticated
  USING (auth.user_id() = user_id);

-- 3. Supporting objects ------------------------------------------------------
CREATE INDEX contacts_user_id_created_at_idx
  ON public.contacts (user_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER contacts_set_updated_at
  BEFORE UPDATE ON public.contacts
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 4. Grants ------------------------------------------------------------------
-- Table-level privileges for signed-in users; RLS then narrows them to own rows.
-- The `anonymous` role is deliberately granted nothing, so signed-out callers
-- are refused before RLS is even consulted.
GRANT SELECT, INSERT, UPDATE, DELETE ON public.contacts TO authenticated;
